stages:
    #- build
    - test
    #- deploy

pytest:
    stage: test
    image: python:3.11-slim-buster
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
    before_script:
        - pip install .[dev]
    script:
        - pytest --cov-report term --cov-report xml:coverage.xml
