stages:
    #- build
    - test
    #- deploy

pytest:
    stage: test
    image: python:3.10-buster
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
    # coverage regex determines the percentage shown in the coverage badge on the project page
    coverage: '/TOTAL.*\s+(\d+%)$/'
    before_script:
        - pip install .[dev]
    script:
        - pytest --cov-report term --cov-report xml:coverage.xml
