stages:
    #- build
    - test
    #- deploy

pytest:
    stage: test
    image: python:3.11
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
    # coverage regex determines the percentage shown in the coverage badge on the project page
    coverage: '/TOTAL.*\s+(\d+%)$/'
    before_script:
        - pip install .[dev]
        - apt-get update && apt-get install -y libgl1 libegl1 libxkbcommon0 libdbus-1-3 # PySide6 dependencies
    script:
        - pytest --cov-report term --cov-report xml:coverage.xml
