stages:
    #- build
    - test
    #- deploy

pytest:
    stage: test
    image: python:3.11-slim-buster
    artifacts:
        when: always
        paths:
            - allure_results
    before_script:
        - pip install -r requirements.txt
    script:
        - pytest -v --alluredir=allure_results
